services:
  rewinder:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../rewinder.toml:/app/rewinder.toml:ro
      - ./data:/data
      - /path/to/media:/media
    logging:
      driver: journald
      options:
        tag: rewinder
    restart: unless-stopped
